<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>userName</name>
   <tag></tag>
   <elementGuidId>af518536-1073-4212-9bba-50a2f983622c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user-4a51b8f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user-4a51b8f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Username&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50d97458-283d-4c5a-a699-67ff896f0668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ec573f4b-d237-4d6e-828b-3c069fc28375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b058058e-bdfa-456f-9c88-9cfbc0676fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>log</value>
      <webElementGuid>d8f49c87-6e2a-4f82-8f33-b3be9ea3778a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user-4a51b8f</value>
      <webElementGuid>0d332453-dd30-457a-82e9-44801647b08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-field elementor-field-textual elementor-size-md</value>
      <webElementGuid>a8062b04-effc-4596-8ee5-09587e23362a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-4a51b8f&quot;)</value>
      <webElementGuid>25822d5e-6f26-4dc2-847b-9959bcc83814</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user-4a51b8f']</value>
      <webElementGuid>401515a0-d910-4798-aec5-57c51b7a4f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/section[2]/div/div/div/section/div/div[2]/div/div[2]/div/form/div/div/input</value>
      <webElementGuid>62cd1adc-7239-49d7-b45b-fa7d72609886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>3807de32-0eb1-43c8-9532-fb7b44bd6c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'log' and @id = 'user-4a51b8f']</value>
      <webElementGuid>e85f413f-7d0b-4f7f-b414-cc845c48cbbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
