<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_EDUCATION</name>
   <tag></tag>
   <elementGuidId>5d20bd67-1e42-4e09-b47a-f7c16d169f36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/section[4]/div/div/div/div[2]/div/div/table/tbody/tr[2]/td[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td:nth-of-type(4) > a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '?group=1056' and (text() = '${category}' or . = '${category}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2ed5f0e8-3fa2-4234-a3c5-949fa8152420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?group=1056</value>
      <webElementGuid>ea9ca21a-28a5-466e-a6e8-958e45606798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${category}</value>
      <webElementGuid>118a9138-357c-460a-a725-16e2497e7b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;elementor elementor-55074 elementor-motion-effects-parent&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-50101714 elementor-section-boxed elementor-section-height-default elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-2591302b&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-6b307d43 elementor-widget elementor-widget-shortcode&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-shortcode&quot;]/table[1]/tbody[1]/tr[2]/td[4]/a[1]</value>
      <webElementGuid>3b0ae832-deaf-4c35-942e-a16f5b3127fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/section[4]/div/div/div/div[2]/div/div/table/tbody/tr[2]/td[4]/a</value>
      <webElementGuid>788f6870-ddc6-4e6f-b365-968913e5eb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'EDUCATION')]</value>
      <webElementGuid>54bccbfb-c031-4df4-93e1-0e8f53328c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DISCIPLE YOUTH'])[1]/following::a[1]</value>
      <webElementGuid>d41a3480-5c2e-486b-aa28-17929f87bf18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENGINEERING'])[1]/preceding::a[1]</value>
      <webElementGuid>cad444d9-9487-49d4-8717-199ce9e5be85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EDUCATION']/parent::*</value>
      <webElementGuid>b365def1-57e6-4649-b70c-37153b3eb57f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '?group=1056')]</value>
      <webElementGuid>16685638-67cc-4792-bfed-49186ce64dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/a</value>
      <webElementGuid>fa2b4557-5781-4857-87ce-6277c6de503a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?group=1056' and (text() = 'EDUCATION' or . = '${category}')]</value>
      <webElementGuid>f4adc5a5-9c87-4c8f-ace5-9129a4e126eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
