<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Partners_background</name>
   <tag></tag>
   <elementGuidId>b2a74937-5a0e-494b-9214-346edcdd58a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.background</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='avatar']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#avatar div >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>068d8f16-97e1-4918-afdb-ce117ae7eec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>background</value>
      <webElementGuid>fb42ad9a-1aa9-4ba0-8baf-310daa5af1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;avatar&quot;)/div[@class=&quot;background&quot;]</value>
      <webElementGuid>63b74b3d-c715-409a-9a91-217c04de286e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='avatar']/div[2]</value>
      <webElementGuid>b4db33e7-d550-4a1d-ad08-b1dfc33abecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>1c9c71da-bc4d-46af-827f-80008083da28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
