<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_QuickStart</name>
   <tag></tag>
   <elementGuidId>0c1b90f1-9e12-4a31-96e5-270577a0a7cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.menu-item.menu-item-type-custom.menu-item-object-custom.menu-item-70202 > a.elementor-sub-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='sm-17135115315781165-2']/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sm-17135115315781165-2 >> internal:role=link[name=&quot;QuickStart&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5796f376-af15-4ea9-85e5-a1884dd49dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://quickstart.missionnext.org/quickstart-home/login-here/?_ga=2.60302253.1006228355.1713511532-1004751840.1713511532</value>
      <webElementGuid>b3282041-72dd-4b21-bd09-fcbe88769c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-sub-item</value>
      <webElementGuid>6962b17c-f446-4734-8476-9ea1c0d915cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QuickStart</value>
      <webElementGuid>f5f477ce-6622-46d3-9912-400f1a8f7592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-17135115315781165-2&quot;)/li[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom menu-item-70202&quot;]/a[@class=&quot;elementor-sub-item&quot;]</value>
      <webElementGuid>f64ecea6-d568-4cd4-9b14-4b0836f99a40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sm-17135115315781165-2']/li[3]/a</value>
      <webElementGuid>0577bccc-1db3-426d-8daf-28a895513c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'QuickStart')]</value>
      <webElementGuid>e9eb5a3a-5ea5-4d86-bc69-961493a548b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Education'])[1]/following::a[1]</value>
      <webElementGuid>668e9dbe-05e5-4f8b-b41e-7b079f47f1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Journey'])[1]/following::a[2]</value>
      <webElementGuid>d275c05d-909f-4d4a-8c5c-c1e89883e182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/preceding::a[1]</value>
      <webElementGuid>0b938a7d-3bb2-4e77-b8e6-c99d157b5b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impact Report'])[1]/preceding::a[2]</value>
      <webElementGuid>43c9ffba-41ab-479b-8e7b-6a5733febb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='QuickStart']/parent::*</value>
      <webElementGuid>799a2e99-3314-4ff6-9463-d145eff4563b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://quickstart.missionnext.org/quickstart-home/login-here/?_ga=2.60302253.1006228355.1713511532-1004751840.1713511532')]</value>
      <webElementGuid>d26a153b-6a0a-4b19-9022-51e19a86bbf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[3]/a</value>
      <webElementGuid>48349f36-cd85-466e-a0a4-24a394f1abf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://quickstart.missionnext.org/quickstart-home/login-here/?_ga=2.60302253.1006228355.1713511532-1004751840.1713511532' and (text() = 'QuickStart' or . = 'QuickStart')]</value>
      <webElementGuid>f3b8c9c4-5137-4f83-9b2c-0f5ebc8c0ad1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
