<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Partners_background</name>
   <tag></tag>
   <elementGuidId>952e9716-d506-4ea7-8628-a6417da9e332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='avatar']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.background</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#avatar div >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98c0c422-df60-4125-b24f-31e88e25051a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>background</value>
      <webElementGuid>f9b1483e-e913-4d78-926e-3cd5822deb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;avatar&quot;)/div[@class=&quot;background&quot;]</value>
      <webElementGuid>6b0c5c5f-7275-4206-b687-3039a2e2d845</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='avatar']/div[2]</value>
      <webElementGuid>0d890bc7-f9c6-4232-8218-aacfca7eaba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>ba822837-34bc-4def-ba25-a4c05a7f4f4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
