<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_pwd</name>
   <tag></tag>
   <elementGuidId>7760ba9c-a494-493c-bccb-027ac4052216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password-15c96ab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password-15c96ab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Password&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e699d2d8-4ea8-4d49-8883-22c50dabe68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f746f3fb-1730-495a-a49c-a6225043ccfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e797d58d-98b4-48af-bdee-9baa7daac2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pwd</value>
      <webElementGuid>c99a4783-dcfe-4ba5-9ef0-0163555251d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-15c96ab</value>
      <webElementGuid>94efa845-434d-494e-9a1e-bdccabe9f798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-field elementor-field-textual elementor-size-md</value>
      <webElementGuid>e98c4609-9277-4c70-b5e8-717f82f62c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-15c96ab&quot;)</value>
      <webElementGuid>e9b5a5b8-319b-4064-bcb3-3d4ef393cfab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password-15c96ab']</value>
      <webElementGuid>7357d81b-fb22-4bdc-a0ff-7bda9fd4a4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/section[2]/div/div/div/section/div/div[2]/div/div/div/form/div/div[2]/input</value>
      <webElementGuid>e3aad42c-1513-4147-9fd6-ae8c59aeef97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a270a8c5-a321-407f-bea3-14d71cb528a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'pwd' and @id = 'password-15c96ab']</value>
      <webElementGuid>97f5e62d-db64-4ec9-961e-ac538c96997e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
