<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_I registered on QuickStart</name>
   <tag></tag>
   <elementGuidId>e215075e-4253-4177-af9e-3f47264360f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='nf-label-field-23-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nf-label-field-23-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a4d724fe-e0ba-4afa-a8b2-f3169dea70b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>nf-field-23-2</value>
      <webElementGuid>82896ade-1dbc-40f3-95f5-eb9e6c7cd7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nf-label-field-23-2</value>
      <webElementGuid>f9799bbc-1ffb-4a5c-b206-e5f2790fb640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I registered on QuickStart</value>
      <webElementGuid>0e18b571-1c01-4cce-9a54-15dec70894fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nf-label-field-23-2&quot;)</value>
      <webElementGuid>488f9d54-961f-4d10-aea7-79272942215f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='nf-label-field-23-2']</value>
      <webElementGuid>2463b207-c5d9-4fba-9992-d621329222e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nf-field-23-wrap']/div[2]/ul/li[3]/label</value>
      <webElementGuid>47f6e7e9-b755-42f5-8e5a-438f8e4083c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I registered on Education'])[1]/following::label[1]</value>
      <webElementGuid>45717ed5-0cd7-49e9-a1c3-67a9b8772985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I registered on Journey'])[1]/following::label[2]</value>
      <webElementGuid>23e42622-91a0-4503-aded-9bd78e709a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::label[1]</value>
      <webElementGuid>01a23adf-03a3-4eba-99fe-12810e8121b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I registered on QuickStart']/parent::*</value>
      <webElementGuid>a0aca965-3361-44c6-a651-f9bcc7595e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/label</value>
      <webElementGuid>c6a83f42-10b3-4a48-a7a1-79bd657e7d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'nf-label-field-23-2' and (text() = 'I registered on QuickStart' or . = 'I registered on QuickStart')]</value>
      <webElementGuid>1f9f5c58-114d-40eb-bdba-8951d51e7012</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
