<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_I registered on Journey</name>
   <tag></tag>
   <elementGuidId>8c3c2f06-b59e-42ea-bb69-19fba324dc2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='nf-label-field-23-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nf-label-field-23-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a5de611d-05b8-43eb-a786-c6b6721b8002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>nf-field-23-0</value>
      <webElementGuid>88da3010-25c1-4c88-9958-c2c9e754d09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nf-label-field-23-0</value>
      <webElementGuid>393d0334-57e8-4c16-8924-f5d95d87991a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nf-checked-label</value>
      <webElementGuid>acb8286a-788e-406d-9e6d-57635fb59fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I registered on Journey</value>
      <webElementGuid>4994e1e1-6b24-4037-bf5e-1b7ec4425d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nf-label-field-23-0&quot;)</value>
      <webElementGuid>05794c26-902a-4f99-9635-b3c255c394ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='nf-label-field-23-0']</value>
      <webElementGuid>e0fe3496-5066-4287-8337-dd1edf3f9bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nf-field-23-wrap']/div[2]/ul/li/label</value>
      <webElementGuid>a569249a-572e-4c41-a8fe-88ff4ef9ac27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::label[1]</value>
      <webElementGuid>ce54c690-21a3-44ef-b65f-1dfbd541e733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I registered on Education'])[1]/preceding::label[1]</value>
      <webElementGuid>f28bff0c-1227-4a9c-a74a-04bc6afc51c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I registered on QuickStart'])[1]/preceding::label[2]</value>
      <webElementGuid>c374d052-6cd3-46fe-8a13-034589e898dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I registered on Journey']/parent::*</value>
      <webElementGuid>aa9704ec-55cc-4040-94b9-510de497669c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/label</value>
      <webElementGuid>ebc1599e-7fde-4957-b0a1-6ef77959aae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'nf-label-field-23-0' and (text() = 'I registered on Journey' or . = 'I registered on Journey')]</value>
      <webElementGuid>78cef0de-03c7-4366-a4bb-72ad6e1bfab3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
