<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_I registered on Education</name>
   <tag></tag>
   <elementGuidId>29338281-cc48-4103-87d4-23f4b7532a1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='nf-label-field-23-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nf-label-field-23-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b723e583-aa94-498a-b56e-04523e76ab70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>nf-field-23-1</value>
      <webElementGuid>eaf5b3d7-a624-4a63-935b-5b41a6837e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nf-label-field-23-1</value>
      <webElementGuid>06956461-9cb9-4557-a18e-ed07fe798fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nf-checked-label</value>
      <webElementGuid>8d51c37e-576f-4fa0-b629-03c35dffc371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I registered on Education</value>
      <webElementGuid>d5854d70-0e53-44ea-ab75-0fc403f98eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nf-label-field-23-1&quot;)</value>
      <webElementGuid>bb8671b7-179b-4371-8d41-bd81e16c2036</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='nf-label-field-23-1']</value>
      <webElementGuid>5892e161-68d1-461a-ac51-6ccef3bf5816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nf-field-23-wrap']/div[2]/ul/li[2]/label</value>
      <webElementGuid>fd539714-369c-4b4a-9752-29f0944a7efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I registered on Journey'])[1]/following::label[1]</value>
      <webElementGuid>7ffb3354-8e8d-4133-8797-c4dc39fe01e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::label[2]</value>
      <webElementGuid>f34a6d5a-1f18-46bc-9c5e-93eb37a91992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I registered on QuickStart'])[1]/preceding::label[1]</value>
      <webElementGuid>eb03436c-ab87-4832-befe-6807c25d54cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I registered on Education']/parent::*</value>
      <webElementGuid>0110b0e7-00a3-4234-81b0-4c93dadb1421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/label</value>
      <webElementGuid>d3d0349f-443d-4aa0-889a-f0b6eb7a6f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'nf-label-field-23-1' and (text() = 'I registered on Education' or . = 'I registered on Education')]</value>
      <webElementGuid>9ab64256-7b78-4e9e-b34e-5f3ded234a31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
