<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_QuickStart</name>
   <tag></tag>
   <elementGuidId>15bcd42c-26b1-472d-8da0-45957c4981f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.menu-item.menu-item-type-custom.menu-item-object-custom.menu-item-70202 > a.elementor-sub-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='sm-17135105439751694-2']/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sm-17135105439751694-2 >> internal:role=link[name=&quot;QuickStart&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1101e019-3927-45fc-85be-5f9b3d3ce301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://quickstart.missionnext.org/quickstart-home/login-here/?_ga=2.123147843.959833710.1713510544-1631200287.1713510544</value>
      <webElementGuid>53a2668e-d851-443d-a9cd-6913dae83ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-sub-item</value>
      <webElementGuid>f0dee207-b5df-4f95-a2e2-73064bd68dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QuickStart</value>
      <webElementGuid>3b208638-5cb6-45b9-a806-05420acc5af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-17135105439751694-2&quot;)/li[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom menu-item-70202&quot;]/a[@class=&quot;elementor-sub-item&quot;]</value>
      <webElementGuid>3c5de627-f365-4685-bcdb-68b472b584e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sm-17135105439751694-2']/li[3]/a</value>
      <webElementGuid>d6244617-3982-49f8-9ca4-c346435da019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'QuickStart')]</value>
      <webElementGuid>782e66d6-4189-4b65-a00d-6a793f05cb04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Education'])[1]/following::a[1]</value>
      <webElementGuid>9715be4a-bc09-4e76-b2bb-88d074cd9640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Journey'])[1]/following::a[2]</value>
      <webElementGuid>9aa9ff0a-beb2-4b3d-9b8b-cc8bbce8871d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/preceding::a[1]</value>
      <webElementGuid>24bb9190-5612-4a2a-883a-ecdcb6862b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impact Report'])[1]/preceding::a[2]</value>
      <webElementGuid>b83302dd-1efc-4ab6-943a-fd35b563d859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='QuickStart']/parent::*</value>
      <webElementGuid>91e1282b-c5d1-44e7-8795-c504f285abcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://quickstart.missionnext.org/quickstart-home/login-here/?_ga=2.123147843.959833710.1713510544-1631200287.1713510544')]</value>
      <webElementGuid>e307ecf4-60f1-40bd-ae50-a2d33d0fd7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[3]/a</value>
      <webElementGuid>0bad973d-3977-4d7c-aad0-cfae1b946955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://quickstart.missionnext.org/quickstart-home/login-here/?_ga=2.123147843.959833710.1713510544-1631200287.1713510544' and (text() = 'QuickStart' or . = 'QuickStart')]</value>
      <webElementGuid>298e7df3-6163-4328-a1bc-a143c4db1e35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
