<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Linkedin_eicon-close</name>
   <tag></tag>
   <elementGuidId>d7cedb00-6c5f-4a40-9bbb-7a27f6378ffd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dialog-close-button.dialog-lightbox-close-button > i.eicon-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='elementor-popup-modal-67215']/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Close&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d797fb36-3399-421e-94e5-e7293233ce4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>eicon-close</value>
      <webElementGuid>bd2bd235-f530-45b2-bad9-7521de57e839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-popup-modal-67215&quot;)/div[@class=&quot;dialog-widget-content dialog-lightbox-widget-content animated&quot;]/a[@class=&quot;dialog-close-button dialog-lightbox-close-button&quot;]/i[@class=&quot;eicon-close&quot;]</value>
      <webElementGuid>b995dd1e-a154-4b22-8306-2e7e851641c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='elementor-popup-modal-67215']/div/a/i</value>
      <webElementGuid>d06ee977-acec-4314-91ac-153e54625cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/i</value>
      <webElementGuid>f0792603-952a-4864-a7fc-dad0cade15e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
